spring:
  profiles:
    active: pre
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driverClassName: com.alipay.oceanbase.jdbc.Driver
      url: jdbc:oceanbase://10.161.136.5:2883/trade?useSSL=false&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&autoReconnect=true&rewriteBatchedStatements=true&sessionVariables=ob_trx_idle_timeout=300000000&sessionVariables=ob_trx_idle_timeout=300000000
      username: trade@trade_single#ywobsingle:1667799384
      password: Sefwa31D3##fea8l
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        allow: ""
        deny: ""
      web-stat-filter:
        enabled: true
      #login-username: admin
      #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  redis:
    timeout: 5000
    password: 1sqRApwxVejE3Qxk
    host: 10.166.50.5
    port: 6381
    database: 0
    max-active: 50 # 连接池最大连接数（使用负值表示没有限制）
    max-idle: 50 # 连接池中的最大空闲连接
    max-wait: 5000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    min-idle: 0 # 连接池中的最小空闲连接
    testOnBorrow: false
dubbo:
  registry:
    address: 10.163.134.1:2181,10.163.134.2:2181,10.163.134.3:2181

domain:
  xf: 'https://app-pre-cstest.fzzqft.com'

home-page:
  instruction: "专业的事，交给专业的人"
  copy-writing:
    - title: "懂你"
      subTitle: "明确投资目标"
    - title: "陪你"
      subTitle: "选择投资策略"
    - title: "帮你"
      subTitle: "系统自动调仓"

organ:
  daily-income-ratio: "1000"